export const productObject = [
  {
    name: "MH200X",
    img: [
      "/MH200X.jpg",
      "/MH200X.jpg",
      "/MH200X.jpg",
      "/MH200X.jpg",
      "/MH200X.jpg",
      "/MH200X.jpg",
    ],
    price: "3,05,000/-",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN R250",
          "Displacement: 250cc with inner balancer",
          "LWHmm: 2145*850*1175",
          "WheelBase/mm: 1390",
          "SeatHeight: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Scrambler 250",
    img: [
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
    ],
    price: "4,55,000/-",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN R250",
          "Displacement: 250cc with inner balancer",
          "LWHmm: 2145*850*1175",
          "WheelBase/mm: 1390",
          "SeatHeight: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Sports 250",
    img: [
      "/Sports250.jpg",
      "/Sports250.jpg",
      "/Sports250.jpg",
      "/Sports250.jpg",
    ],
    price: "Nrs 3,70,000/-",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN R250",
          "Displacement: 250cc with inner balancer",
          "LWHmm: 2145*850*1175",
          "WheelBase/mm: 1390",
          "SeatHeight: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Tekken R250",
    img: [
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
    ],
    price: "3,95,000/-",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN R250",
          "Displacement: 250cc with inner balancer",
          "LWHmm: 2145*850*1175",
          "WheelBase/mm: 1390",
          "SeatHeight: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "X-Torque 250",
    img: [
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
    ],
    price: "3,90,000/-",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN R250",
          "Displacement: 250cc with inner balancer",
          "LWHmm: 2145*850*1175",
          "WheelBase/mm: 1390",
          "SeatHeight: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
];
