export const productObject = [
  {
    name: "MH200X",
    img: [
      "/MH200X1.jpg",
      "/MH200X1.jpg",
      "/MH200X1.jpg",
      "/MH200X1.jpg",
      "/MH200X1.jpg",
      "/MH200X1.jpg",
    ],
    displacement: "200cc with inner balancer",
    price: "3,75,000/-",
    lwh_mm: "2080*780*1150",
    description: `Though the name ‘Motorhead’ may be relatively new in Nepal, the company’s history dates back to 2005 when it was first established. Fast forward to today, the Chinese motorcycle manufacturer produces more than 200,000 units a year and their products are sold all over the world, primarily establishing itself in the automotive markets of South America, Middle East, Southeast Asia and Africa. Nowadays, the company is focussed on launching exciting new products at affordable prices in Nepal.`,
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model:  MH200X",
          "Displacement: 200cc with inner balancer",
          "LWHmm: 2080*780*11505",
          "WheelBase/mm: 1370",
          "SeatHeight: 810",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "NetWeightGrossWeight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front):  3.50-17",
          "Tyre Size (Rear): 4.60-17",
          "Brake Type:  Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Mechanical speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 12 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 15 H.p/8000MP",
          "Max Torque/N.m/r/min: 15N.m/ 6500 rpm",
          "Top Speed: 100km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: BROSS Steel Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Scrambler 250",
    img: [
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
      "/Scrambler250.jpg",
    ],
    price: "4,55,000/-",
    displacement: "250cc with inner balancer",
    lwh_mm: "2145*850*1175",
    weight: "",
    description:
      "If any movie from the Mad Max series were to be shot and directed in Nepal, we can definitely see the Motorhead Scrambler in at least one of the scenes. That’s purely going by the aesthetic appeal of the Scrambler, which is its strongest suit. The post-apocalyptic retro, steam-punk appeal of the Motorhead Scrambler is a definite crowd-puller, but living up to the aesthetics is a long order. Where does it stand in that spectrum ?",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: SCRAMBLER 250",
          "Displacement: 250cc with inner balancer",
          "L*W*H／mm: 2145*850*1175",
          "Wheel Base/mm: 1390",
          "Seat Height: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "Net.Weight/Gross.Weight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,Oil cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: Steel Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Others: USB charger",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Sports 250",
    img: [
      "/Sports250.jpg",
      "/Sports250.jpg",
      "/Sports250.jpg",
      "/Sports250.jpg",
    ],
    price: "Nrs 3,70,000/-",
    displacement: "250cc with inner balancer",
    lwh_mm: "2130*860*1200",
    description:
      "It is perfect for those looking to ride a dirt bike but don't want to shell out a ton of cash. The preppy engine and seat height along with its massive fuel tank make it a capable city commuter. It does have a few niggles here and there but the riding experience is surprisingly good for its price",
    weight: "122KG/143KG",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: SPORTS 250",
          "Displacement: 250cc with inner balancer",
          "L*W*H／mm: 2130*860*1200",
          "Wheel Base/mm: 1415",
          "Seat Height: 900",
          "Sprocket: Fr:520-13T; Re:520-43T",
          "Net.Weight/Gross.Weight: 122KG/143KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 80/100-21",
          "Tyre Size (Rear): 110/100-18",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Mechanical speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 7 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: High Performance Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "Tekken R250",
    img: [
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
      "/tekken250.jpg",
    ],
    price: "3,95,000/-",
    displacement: "250cc with inner balancer",
    lwh_mm: "2145*850*1175",
    tag: "AGV, Full-face",
    description:
      "Featuring an attractive graphics, Tekken 250 consists of the double exhaust with steel muffler pipes. The seat height of 820mm provides a tall and comfortable riding posture to the crossover. The bike consists of a fuel tank of 14 liters with an expected mileage of around 40kmpl.",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: TEKKEN 250",
          "Displacement: 250cc with inner balancer",
          "L*W*H／mm: 2145*850*1175",
          "Wheel Base/mm: 1390",
          "Seat Height: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "Net.Weight/Gross.Weight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 110/90-17",
          "Tyre Size (Rear): 130/80-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },

  {
    name: "X-Torque 250",
    img: [
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
      "/X-Torque250.jpg",
    ],
    price: "3,90,000/-",
    displacement: "250cc with inner balancer",
    lwh_mm: "2145*850*1175",
    weight: "133KG/151KG",
    description:
      "The new X-torque 250 is powered by a 250cc air-cooled single-cylinder, 2 valve engine with a variety of alluring inside features. The bike’s engine is mated with a 5-speed gearbox transmission while it has a top speed of 120km/l. More on, highlighting on the power performance, the new X-torque 250 produces a power of 20bhp and a peak torque of 19Nm. It provides a mileage of 40km. The braking is handled by disc brakes on both the front and rear sides. Similarly, the two-wheeler has a wheelbase of 1390mm while an inverted suspension is integrated on the front along with an oil-dumper mono-shock suspension on the rear.",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Model: X TORQUE",
          "Displacement: 250cc with inner balancer",
          "L*W*H／mm: 2145*850*1175",
          "Wheel Base/mm: 1390",
          "Seat Height: 820",
          "Sprocket: Fr:520-13T; Re:520-41T",
          "Net.Weight/Gross.Weight: 133KG/151KG",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front): 3.50-17",
          "Tyre Size (Rear): 4.60-17",
          "Brake Type: Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Mechanical speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 12 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2.1L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
  {
    name: "MH150R",
    img: [
      "/MH150R.jpg",
      "/MH150R.jpg",
      "/MH150R.jpg",
      "/MH150R.jpg",
      "/MH150R.jpg",
      "/MH150R.jpg",
    ],
    price: "3,05,000/-",
    displacement: "149 cc",
    lwh_mm: "2080*780*1150",
    weight: "118 kg/ 137 kg",
    description:
      "Motorhead MH 150R is one of the perfect bikes for a dirt bike experience, and those who are dirt bike enthusiasts have deeply accepted the brand. The company has gathered a huge fanbase in a short time in Nepal and is a Guinness world record-holding company. The company holds the world record for the longest journey in a motorcycle, traveling over 35,000km in a single journey.",
    tabs: [
      {
        id: 1,
        name: "Description",
        href: "#",
        current: true,
        details: [
          "Bore: 65.5*66.2 mm",
          "Clutch: international",
          "Configuration: 9:2:1",
          "Cooling System: Air cooled engine",
          "Displacement: 149 cc",
          "Engine Type: Zongshen 150cc",
          "Fuel Delivery System: Pressure and Splash",
          "Fuel Type: carburetor Pz 27/h",
          "Gear Box: 5 gear",
          "Max. Power: 13 bhp",
          "Max. Torque: 14 n.m/6500 rpm",
          "Mileage: 45 km",
          "No. of Cylinders: 1",
          "Starting: electric and kick start",
          "Stroke: 4",
          "Top Speed: 120 km/hr",
          "Valves Per Cylinder: 2",
        ],
      },
      {
        id: 2,
        name: "Frame Suspension",
        current: false,
        details: [
          "Front suspension: Inverted front shocks",
          "Rear suspension: center shock+oil damp",
        ],
      },
      {
        id: 3,
        name: "Type & Brake",
        current: false,
        details: [
          "Tyre Size (Front):  3.50-17",
          "Tyre Size (Rear): 4.60-17",
          "Brake Type:  Front&rear hydraulic disc brakes",
        ],
      },
      {
        id: 4,
        name: "Electricals",
        current: false,
        details: [
          "Speedmeter: Digital speedometer",
          "Starting Method: Electric start",
        ],
      },
      {
        id: 5,
        name: "Engine",
        current: false,
        details: [
          "Engine: Loncin RE250",
          "Engine Type: Electric start,6gears,air cool,12V/12pole",
          "Configuration: Carburetor PZ30",
          "Fuel Tank: 14 L",
          "Bore*stroke/mm: 65.5×66.2mm",
          "Max Power/km/r/min: 19 H.p/8000MP",
          "Max Torque/N.m/r/min: 20N.m/ 6500 rpm",
          "Top Speed: 120km/h",
          "Ignition method: DC-CDI",
          "Lubrication method: Pressure and Splash",
          "Muffler: CRF Alloy Muffler",
        ],
      },
      {
        id: 6,
        name: "Transmission",
        current: false,
        details: [
          "No of Gears: 6 Gears, manual clutch",
          "Gearshift method: International",
          "Min.Fuel Consumption: 2L/100KM",
          "Clutch method: International",
          "Compression Ratio: 9.2:1",
          "Special configuration: Headlight,LED signal/taillights",

          "* as per company standard; ** Specifications are subject to change",
        ],
      },
    ],
  },
];
